-- LDD : 
-- LMD : LANGAGE DE MANIULATION DES DONNEES 
-- INSERT , UPDATE ET DELETE 

-- INSERER DES LIGNES DANS UNE TABLE
    INSERT INTO produits ( LIBELLE,PRIX,qtestock) VALUES('acer S900',9000,10)

-- SUPPRIMER UN LIGNE  : DELETE
--  DELETE  FROM produits WHERE IDENTIFIANT=5

-- MODIFIER UNE DONNEE  :
-- UPDATE produits SET PRIX=5000 WHERE  LIBELLE='DELL D8'
 -- SELECT * FROM PRODUITS
 -- LES 5 CONTRAINTES DES BASES DE DONNEES : 
-- PRIMARY KEY : INFO UNIQUE ET OBLIGATOIRE
-- NOT NULL : CHAMPS EST OBLIGATOIRE
-- UNIQUE : PAS DE DOUBLONS 
-- CHECK : IF ,EXEMPLE : CHECK (PRIX>=0)
--  FOREIGN KEY 
--  ALTER TABLE produits  ADD CONSTRAINT obli_prix  UNIQUE(libelle)
 -- alter table produits add qtestock int not null 
-- DESC produits

